sudo: required
services: 
  - docker 

before_install:
  - docker build -t ealkhannaq/docker-react -f Dockerfile.dev .
#testing the code
script:
  - docker run ealkhannaq/docker-react npm run test -- --coverage